---
title: Betta Web Design
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
  portfolio:
    title: Portfolio
    output: true
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
  uploads:
    title: Uploads
    output: true
  locations:
    title: locations
    output: true
  projects:
    title: projects
    output: true
email: Matherne.Projects@gmail.com
description: Web Design and Support based in Austin Texas.
url: http://amatherne.github.io/bettadesign
twitter_username: matherne_austin
github_username: amatherne
excerpt_separator: "<!--break-->"
markdown: kramdown
permalink: pretty
defaults:
  -
    scope:
      path: ''
      type: blogs
    values:
      layout: blog-post
      website: ''
      screenshots: 
        shot: ''
        caption: ''
      tech: []