---
title: Betta Web Design
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
  portfolio:
    title: Portfolio
    output: true
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Ethan"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      colors: ["red", "green", "blue"]
      layout: "project"
  -
    scope:
      path: ""
      type: "locations"
    values:
      map:
        latitude: 
        longitude: 
email: Matherne.Projects@gmail.com
description: Web Design and Support based in Austin Texas.
url: http://amatherne.github.io/
twitter_username: matherne_austin
github_username: amatherne
excerpt_separator: "<!--break-->"
markdown: kramdown
